[[redirects]]
  from = "/"
  to = "/teams"
  status=301!


[[redirects]]
  from = "/"
  to = "/classes"
  status=301!

[[redirects]]
  from = "/teams"
  to = "/"
  status=301!

[[redirects]]
  from = "/classes"
  to = "/"
  status=301!